version: '3'

services:
  web:
    build: ./web
    container_name: magento-web
    volumes:
      - ../magento:/var/www/html:cached
  mysql:
    image: mysql/mysql-server:5.7
    container_name: magento-mysql
    volumes:
      - './db/data:/var/lib/mysql:cached'
      - './db/init:/docker-entrypoint-initdb.d:cached'
    expose:
      - 3306
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'magento'
      MYSQL_USER: 'magento'
      MYSQL_PASSWORD: 'secret'